test4

diff --git a/.github/workflows/test-app.yml b/.github/workflows/test-app.yml
--- a/.github/workflows/test-app.yml
+++ b/.github/workflows/test-app.yml
@@ -81,8 +81,18 @@ jobs:
         APP_ADMIN_NAME: ${{secrets.APP_ADMIN_NAME}}
 
     - name: Publish Test Report
+      id: coverageComment
       uses: MishaKav/pytest-coverage-comment@main
       with:
         junitxml-path: res-test.xml
         pytest-xml-coverage-path: coverage.xml
-        minimum_coverage: 90
+
+    - name: Check the output coverage
+      run: |
+        COVERAGE=$(grep -o 'line-rate="[0-9]*\.[0-9]*"' coverage.xml | sed 's/line-rate=//;s/"//g')
+        MINIMUM_COVERAGE=0.80
+        if (( $(echo "$COVERAGE < $MINIMUM_COVERAGE" | bc -l) )); then
+          echo "Coverage $COVERAGE is below the minimum required $MINIMUM_COVERAGE"
+          exit 1
+        fi
+
